services:
    nginx:
        image: nginx:1.21.1
        container_name: laravel-nginx
        ports:
            - "80:80"
        volumes:
            - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./backend/src:/var/www/
        depends_on:
            - php

    php:
        build: ./backend/docker/php
        container_name: laravel-php
        volumes:
            - ./backend/src:/var/www/

    mysql:
        image: mysql:8.0.26
        container_name: laravel-mysql
        platform: linux/amd64
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_pass
        command:
            mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - ./backend/docker/mysql/data:/var/lib/mysql
            - ./backend/docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel-phpmyadmin
        platform: linux/amd64
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=laravel_user
            - PMA_PASSWORD=laravel_pass
        depends_on:
            - mysql
        ports:
            - 8080:80

    # frontend:
    #   build:
    #     context: ./frontend
    #   container_name: react-frontend
    #   working_dir: /app
    #   volumes:
    #     - ./frontend:/app
    #   ports:
    #     - "3000:3000"
    #   command: sh -c "npm install && npm start"
    #   depends_on:
    #     - php